# Environment

exec_always dbus-update-activation-environment --systemd WAYLAND_DISPLAY XDG_CURRENT_DESKTOP=sway



# Wallpaper is handled natively in output.conf (output * bg)



# Status bar

exec_always waybar



# Notifications

exec mako



# Authentication agent

exec /usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1



# Network tray

exec nm-applet



# Clipboard

exec wl-paste \
-t text \
--watch cliphist store