# Main modifier key

set $mod Mod4


# Applications

set $terminal foot
set $launcher wofi --show drun
set $browser firefox


# Colors

set $background #1e1e2e
set $foreground #cdd6f4

set $accent #89b4fa