# =====================================
# Modern Catppuccin Starship
# =====================================


add_newline = true


format = """
$username\
$hostname\
$directory\
$git_branch\
$git_status\
$python\
$nodejs\
$rust\
$docker_context\
$character
"""


[directory]

style = "bold blue"



[git_branch]

symbol = " "

style = "bold purple"



[git_status]

style = "yellow"



[python]

symbol = " "



[nodejs]

symbol = " "



[rust]

symbol = " "



[docker_context]

symbol = " "



[character]

success_symbol = "[❯](bold green)"

error_symbol = "[❯](bold red)"