sway
waybar
wofi
foot
mako
swaybg
swayidle
swaylock
grim
slurp
wl-clipboard
cliphist
pipewire
pipewire-pulse
pipewire-alsa
wireplumber
brightnessctl
playerctl
greetd
greetd-tuigreet
xdg-desktop-portal
xdg-desktop-portal-wlr
polkit-gnome
bluez
bluez-utils
blueman
power-profiles-daemon
